# render.yaml
databases:
  - name: cuba_api_db
    plan: free
    databaseName: cuba_api_db
    user: cuba_api_db

services:
  - type: web
    plan: free
    name: cuba_api
    runtime: docker
    envVars:
      # Database
      - key: DATABASE_URL
        fromDatabase:
          name: cuba_api_db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      # Laravel
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      # Image-specific vars (richarvey/nginx-php-fpm)
      - key: WEBROOT
        value: /var/www/html/public
      - key: RUN_SCRIPTS
        value: 1
      - key: REAL_IP_HEADER
        value: 1
      - key: SKIP_COMPOSER
        value: 1